update

diff --git a/extra/fcron/build b/extra/fcron/build
--- a/extra/fcron/build
+++ b/extra/fcron/build
@@ -1,15 +1,15 @@
 #!/bin/sh -e
 
-# NOTE: Build fails as USER "chown: changing ownership of pkg/fcron/usr/sbin : Operation not permitted"
+# Build fails as "USER".
+#    "chown: changing ownership of pkg/fcron/usr/sbin : Operation not permitted"
 
 if [ "$(id -u)" != 0 ]; then
-   echo "#####################################"
-   echo "# [ ! ] NEED TO BUILD AS ROOT [ ! ] #"
-   echo "#                                   #"
-   echo "#        ssu -p kiss b fcron        #"
-   echo "#####################################"
-
-   exit 1
+    echo "#####################################"
+    echo "# [ ! ] NEED TO BUILD AS ROOT [ ! ] #"
+    echo "#                                   #"
+    echo "#        ssu -p kiss b fcron        #"
+    echo "#####################################"
+    exit 1
 fi
 
 getent group fcron || addgroup -S -g 997 fcron
@@ -20,7 +20,7 @@ mv -f _ script/user-group
 
 chmod +x script/user-group
 
-# Remove documentation.
+# Remove docs.
 sed 's/ fr//' doc/Makefile.in > _
 mv -f _ doc/Makefile.in
 
