update

diff --git a/extra/nodejs/build b/extra/nodejs/build
--- a/extra/nodejs/build
+++ b/extra/nodejs/build
@@ -14,8 +14,8 @@ mv -f _ deps/corepack/dist/vendors_yarn_berry_cache_proxy-agent-npm-5_0_0-41772f
     mv -f _ node.gyp
 }
 
-# nodejs 18.4.2 LTS will fail to build with '-march=native' & 'core2'.
-march=$(gcc -march=native -Q --help=target | grep -- -march | grep -o core2 || true)
+# nodejs 18.4.2 LTS will fail to build with core2 cpu & '-march=native'.
+march=$(gcc -march=native -Q --help=target | grep -- -march | grep -qo core2 || true)
 
 if [ "$march" ]; then
    export CXXFLAGS="$CXXFLAGS -march=$march"
